// This is a generated file 
// Generated by ResouceKit 
// You can write custom imoprt XXXX logic
import UIKit
protocol XibProtocol {
	var name: String { get } 
	 func nib() -> UINib
}
extension UITableView { 
	internal func register(_ nib: XibProtocol) -> Void {
		register(nib.nib(), forCellReuseIdentifier: nib.name)
	}
	internal func register(nibs: [XibProtocol]) -> Void {
		nibs.forEach(register)
	}
	 
} 

extension UICollectionView { 
	internal func register(_ nib: XibProtocol) -> Void {
		register(nib.nib(), forCellWithReuseIdentifier: nib.name)
	}
	internal func register(nibs: [XibProtocol]) -> Void {
		nibs.forEach(register)
	}
	 
} 

extension ViewController { 
	class func initialViewController() -> ViewController {
		let storyboard = UIStoryboard(name: "ViewController", bundle: nil) 
		let viewController = storyboard.instantiateInitialViewController() as! ViewController
		return viewController
	}
	 
} 
extension UIImage { 
	
	struct Asset {
		static let add: UIImage = UIImage(named: "add")!
		static let fb: UIImage = UIImage(named: "fb")!
		static let gh: UIImage = UIImage(named: "gh")!
		static let ic_apps_48pt: UIImage = UIImage(named: "ic_apps_48pt")!
		static let ic_local_see_48pt: UIImage = UIImage(named: "ic_local_see_48pt")!
		static let ic_message_48pt: UIImage = UIImage(named: "ic_message_48pt")!
		static let ic_send_48pt: UIImage = UIImage(named: "ic_send_48pt")!
		static let ic_timer_48pt: UIImage = UIImage(named: "ic_timer_48pt")!
		static let insta: UIImage = UIImage(named: "insta")!
		static let link: UIImage = UIImage(named: "link")!
		static let off: UIImage = UIImage(named: "off")!
		static let priority_high: UIImage = UIImage(named: "priority_high")!
		static let tm: UIImage = UIImage(named: "tm")!
		static let tw: UIImage = UIImage(named: "tw")!
	
	}
	struct Resource {
	
	
	} 
} 

extension String { 
	
	struct Localized {
	
	
	} 
} 

